UBO-188 Fixed xpath to mods:dateIssued in badge for year and citation…
MyCoRe-Org/ubo pull request #227
Opened 2022-10-18 11:02 UTC by Possommi

… of Überordnung (In:)

2022-10-20 11:22 UTC, fluetze requested changes
Let's further simplify and test the following, also to make the xPaths more precise:

```
<xsl:when test="descendant-or-self::mods:mods/mods:dateIssued">
        <xsl:apply-templates select="descendant-or-self::mods:mods/mods:dateIssued[1]" mode="label-year-badge"/>
      </xsl:when>
      <xsl:otherwise>
          <xsl:apply-templates select="descendant-or-self::mods:mods/mods:relatedItem[@type='host']/mods:dateIssued[1]" mode="label-year-badge"/>
      </xsl:otherwise>
```

2022-10-20 11:54 UTC, kponten commented
"What if we have, for example, an article within proceedings. The host is proceedings and contains the dateIssued, the article has no separate dateIssued. Does this xPath find the dateIssued?" -> It does

2022-10-20 11:55 UTC, kponten approved these changes

2022-11-04 11:07 UTC, Possommi commented
> Let's further simplify and test the following, also to make the xPaths more precise:
> 
> ```
> <xsl:when test="descendant-or-self::mods:mods/mods:dateIssued">
>         <xsl:apply-templates select="descendant-or-self::mods:mods/mods:dateIssued[1]" mode="label-year-badge"/>
>       </xsl:when>
>       <xsl:otherwise>
>           <xsl:apply-templates select="descendant-or-self::mods:mods/mods:relatedItem[@type='host']/mods:dateIssued[1]" mode="label-year-badge"/>
>       </xsl:otherwise>
> ```

this won't display the badged anymore

2022-11-04 11:28 UTC, merged