UBO-291 Added xslt-convert-mods-genre.xsl to convert mods:genre to mods:genre with authority and value uri
MyCoRe-Org/ubo pull request #342
Opened 2024-01-03 08:22 UTC by Possommi

2024-01-09 11:25 UTC, fluetze requested changes
You could simplify the code further:

Instead of
`<mods:genre type="intern" authorityURI="{concat($WebApplicationBaseURL,'classifications/ubogenre')}" valueURI="{concat($WebApplicationBaseURL,'classifications/ubogenre#dissertation')}" />`

just write
`<mods:genre type="intern" authorityURI="$WebApplicationBaseURL}classifications/ubogenre" valueURI="{$WebApplicationBaseURL}classifications/ubogenre#dissertation" />`

2024-01-10 08:48 UTC, Possommi commented
Simplified generation of valueURI and authorityURI in Stylesheets

2024-01-10 09:08 UTC, fluetze requested changes

2024-01-10 09:08 UTC, fluetze commented on ubo-common/src/main/resources/xsl/import/genre2genre.xsl
Not sure, do we still need the
<xsl:when test="mods:genre[@type='intern']">... ?

2024-01-10 09:08 UTC, fluetze commented on ubo-common/src/main/resources/xsl/import/genre2genre.xsl
Move the <xsl:value-of select="concat($WebApplicationBaseURL,'classifications/ubogenre#')" />
to the top right below 
 <xsl:attribute name="valueURI">
 since it is always the same for each xsl:when

2024-01-10 09:08 UTC, fluetze commented on ubo-common/src/main/resources/xsl/import/genre2genre.xsl
This is duplicate:
                <xsl:value-of select="$firstGenre" />
                <xsl:value-of select="concat($WebApplicationBaseURL,'classifications/ubogenre#', $firstGenre)" />

2024-01-10 09:08 UTC, fluetze commented on ubo-common/src/main/resources/xsl/migration/migrate-mods-genre.xsl
The
<xsl:copy-of select="@*"/>
will copy the @type='intern' - do we still need / want that attribute?

2024-01-10 09:08 UTC, fluetze commented on ubo-common/src/main/resources/xsl/mods-postprocessor.xsl
The
<xsl:copy-of select="@*"/>
will copy the @type='intern' - do we still need / want that attribute?

2024-01-10 10:07 UTC, Possommi commented on ubo-common/src/main/resources/xsl/import/aleph2mods.xsl
mea culpa

2024-01-10 10:17 UTC, Possommi commented on ubo-common/src/main/resources/xsl/import/csv2xml-iaq2mods.xsl
@fluetze fixed

2024-01-10 10:20 UTC, Possommi commented on ubo-common/src/main/resources/xsl/import/genre2genre.xsl
I would like to keep it as some stylesheets set a mods:genre[@type='internal'] during import and this check ensures the mods:genre element is kept

2024-01-10 10:26 UTC, Possommi commented on ubo-common/src/main/resources/xsl/import/genre2genre.xsl
@fluetze fixed

2024-01-10 10:26 UTC, Possommi commented on ubo-common/src/main/resources/xsl/import/genre2genre.xsl
@fluetze fixed

2024-01-10 10:28 UTC, Possommi commented on ubo-common/src/main/resources/xsl/migration/migrate-mods-genre.xsl
yes as of https://github.com/MyCoRe-Org/ubo/pull/342#discussion_r1447169254

2024-01-10 10:28 UTC, Possommi commented on ubo-common/src/main/resources/xsl/mods-postprocessor.xsl
yes

2024-03-26 10:50 UTC, kkrebs approved these changes

2024-04-20 09:55 UTC, merged