Issues/ubo 295 publication event handler creates redundant users in database
MyCoRe-Org/ubo pull request #354
Opened 2024-02-02 10:12 UTC by erodde

2024-02-02 12:51 UTC, fluetze requested changes

2024-02-05 10:23 UTC, erodde commented on ubo-common/src/test/resources/mcr-roles.xml
Roles are now set inside the unit test

2024-02-05 10:26 UTC, erodde commented on ubo-common/src/test/resources/PublicationEventHandlerTest/junit_mods_00000001.xml
Fixed indent in XML-Files and formatted all changed Java-files with formatter-file "mycore-javastyle.xml". There is still changed formatting of Java-files.

2024-02-06 09:12 UTC, fluetze approved these changes

2024-02-06 16:49 UTC, kkrebs approved these changes

2024-02-06 16:49 UTC, merged