UBO-218 Added workaround for a hidden submit button
MyCoRe-Org/ubo pull request #362
Opened 2024-02-20 10:00 UTC by kponten

2024-02-20 10:30 UTC, fluetze approved these changes

2024-02-20 11:54 UTC, fluetze requested changes
See
https://www.mycore.de/documentation/frontend/frontend_xeditor/
on how to define submit buttons.
The xed:target is missing. But: We do not know the target here.
So I think this will not work.

2024-02-22 12:14 UTC, kponten commented
Now it works

2024-02-22 14:08 UTC, fluetze approved these changes

2024-02-23 14:40 UTC, merged