Issues/ubo 348 large rfc5646 classification makes editor slow
MyCoRe-Org/ubo pull request #408
Opened 2024-07-31 14:31 UTC by sebhofmann

To add the right permissions you need to add run `bin/ubo.sh update permission read for id restapi:/classifications with rulefile ubo-cli/src/main/setup/acl/acl-rule-always-allowed.xml described by always allowed` or add `read restapi:/classifications always allowed`

2024-08-01 09:10 UTC, Possommi requested changes
Works like a charme. But to avoid confusion a placeholder like _type to search_ would be a good thing.

2024-08-02 09:18 UTC, Possommi approved these changes

2024-08-02 09:28 UTC, Possommi requested changes
- the new language input is not working in repeaters (`mods:language/mods:languageTerm`)
  - when adding a new line the value previously set disappears 
- Javascript error when loading the xEditorform
- when a language has already been set the input remains empty on editor load

2024-08-02 14:17 UTC, sebhofmann commented
Should work now.

2024-08-05 06:56 UTC, Possommi approved these changes

2024-08-05 07:38 UTC, merged